# Generated by Django 4.0.5 on 2022-06-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dip',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='asleep',
            name='habit',
        ),
        migrations.AlterField(
            model_name='asleep',
            name='note',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Awake',
        ),
        migrations.DeleteModel(
            name='Dip',
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
    ]
