# Generated by Django 4.0.5 on 2022-06-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_dip_habit_remove_asleep_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asleep',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
