# Generated by Django 4.0.5 on 2022-06-28 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_asleep_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asleep',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='asleep',
            name='asleep_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 6, 28, 23, 11, 5, 105548)),
        ),
    ]
