# Generated by Django 4.0.5 on 2022-06-29 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_asleep_asleep_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awake_date', models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 22, 20, 880571))),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dip_date', models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 22, 20, 880687))),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DreamNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_date', models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 22, 20, 880799))),
                ('note', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='asleep',
            name='asleep_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 22, 20, 880429)),
        ),
    ]
