# Generated by Django 4.0.5 on 2022-06-29 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_awake_dip_dreamnote_alter_asleep_asleep_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asleep',
            name='asleep_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 25, 30, 231768)),
        ),
        migrations.AlterField(
            model_name='awake',
            name='awake_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 25, 30, 231911)),
        ),
        migrations.AlterField(
            model_name='dip',
            name='dip_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 25, 30, 232035)),
        ),
        migrations.AlterField(
            model_name='dreamnote',
            name='dream_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 25, 30, 232144)),
        ),
    ]
