# Generated by Django 4.0.5 on 2022-06-29 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_asleep_asleep_date_alter_awake_awake_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asleep',
            name='asleep_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 33, 42, 915245)),
        ),
        migrations.AlterField(
            model_name='awake',
            name='awake_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 33, 42, 915392)),
        ),
        migrations.AlterField(
            model_name='dip',
            name='dip_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 33, 42, 915515)),
        ),
        migrations.AlterField(
            model_name='dreamnote',
            name='dream_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 3, 33, 42, 915623)),
        ),
    ]
