# Generated by Django 4.0.5 on 2022-06-29 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_alter_asleep_asleep_date_alter_awake_awake_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asleep',
            name='asleep_date',
        ),
        migrations.RemoveField(
            model_name='awake',
            name='awake_date',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='dip_date',
        ),
        migrations.RemoveField(
            model_name='dreamnote',
            name='dream_date',
        ),
        migrations.AddField(
            model_name='asleep',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 19, 45, 40, 390226)),
        ),
        migrations.AddField(
            model_name='awake',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 19, 45, 40, 390374)),
        ),
        migrations.AddField(
            model_name='dip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 19, 45, 40, 390487)),
        ),
        migrations.AddField(
            model_name='dreamnote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 19, 45, 40, 390586)),
        ),
    ]
