# Generated by Django 4.0.5 on 2022-06-29 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_remove_asleep_asleep_date_remove_awake_awake_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asleep',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 20, 26, 20, 967051)),
        ),
        migrations.AlterField(
            model_name='awake',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 20, 26, 20, 967200)),
        ),
        migrations.AlterField(
            model_name='dip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 20, 26, 20, 967315)),
        ),
        migrations.AlterField(
            model_name='dreamnote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 20, 26, 20, 967415)),
        ),
    ]
