# Generated by Django 4.0.5 on 2022-07-02 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_alter_asleep_date_alter_awake_date_alter_dip_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asleep',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 19, 39, 56, 468764)),
        ),
        migrations.AlterField(
            model_name='awake',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 19, 39, 56, 468914)),
        ),
        migrations.AlterField(
            model_name='dip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 19, 39, 56, 469032)),
        ),
        migrations.AlterField(
            model_name='dreamnote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 19, 39, 56, 469137)),
        ),
    ]
