# Generated by Django 4.0.5 on 2022-07-12 12:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0014_alter_asleep_date_alter_awake_date_alter_dip_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asleep',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asleep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awake',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awake', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreamnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dream_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asleep',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 12, 56, 54, 143134)),
        ),
        migrations.AlterField(
            model_name='awake',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 12, 56, 54, 143325)),
        ),
        migrations.AlterField(
            model_name='dip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 12, 56, 54, 143485)),
        ),
        migrations.AlterField(
            model_name='dreamnote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 12, 56, 54, 143632)),
        ),
    ]
